# See https://github.com/lowlighter/metrics for documentation
# This worflow is scheduled for every hour, and also run after each commit (GitHub action excluded) on master/main branch

name: Metrics-Runner
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

    - name: Metrics classic
      if: ${{ success() || failure() }}
      uses: lowlighter/metrics@master
      with:
        # Your filename
        filename: img/metrics.classic.svg
        # Your GitHub token
        token: ${{ secrets.METRICS_TOKEN }}
        # Options
        user: felixhollitzer
        template: classic
        base: header, activity, community, repositories, metadata
        config_timezone: Europe/Berlin
        repositories: 1000
        output_action: pull-request


    - name: Metrics terminal
      if: ${{ success() || failure() }}
      uses: lowlighter/metrics@master
      with:
        # Your filename
        filename: img/metrics.terminal.svg
        # Your GitHub token
        token: ${{ secrets.METRICS_TOKEN }}
        # Options
        user: felixhollitzer
        template: terminal
        base: header, activity, community, repositories, metadata
        config_timezone: Europe/Berlin
        repositories: 1000
        output_action: pull-request

    - name: Isometric calendar (half-year)
      if: ${{ success() || failure() }}
      uses: lowlighter/metrics@master
      with:
        # Your filename
        filename: img/cal.isometric.half-year.svg
        # Your GitHub token
        token: ${{ secrets.METRICS_TOKEN }}
        # Options
        user: felixhollitzer
        template: classic
        base: ""
        config_timezone: Europe/Berlin
        plugin_isocalendar: yes
        plugin_isocalendar_duration: half-year
        repositories: 1000
        output_action: pull-request

    - name: Isometric calendar (full-year)
      if: ${{ success() || failure() }}
      uses: lowlighter/metrics@master
      with:
        # Your filename
        filename: img/cal.isometric.full-year.svg
        # Your GitHub token
        token: ${{ secrets.METRICS_TOKEN }}
        # Options
        user: felixhollitzer
        template: classic
        base: ""
        config_timezone: Europe/Berlin
        plugin_isocalendar: yes
        plugin_isocalendar_duration: full-year
        repositories: 1000
        output_action: pull-request

    - name: Coding habits
      if: ${{ success() || failure() }}
      uses: lowlighter/metrics@master
      with:
        # Your filename
        filename: img/habits.svg
        # Your GitHub token
        token: ${{ secrets.METRICS_TOKEN }}
        # Options
        user: felixhollitzer
        template: classic
        base: ""
        config_timezone: Europe/Berlin
        plugin_habits: yes
        plugin_habits_days: 14
        plugin_habits_facts: yes
        plugin_habits_from: 200
        repositories: 1000
        output_action: pull-request

    - name: Achivements X
      if: ${{ success() || failure() }}
      uses: lowlighter/metrics@master
      with:
        # Your filename
        filename: img/achivements.x.svg
        # Your GitHub token
        token: ${{ secrets.METRICS_TOKEN }}
        # Options
        user: felixhollitzer
        template: classic
        base: ""
        config_timezone: Europe/Berlin
        plugin_achievements: yes
        plugin_achievements_display: detailed
        plugin_achievements_secrets: yes
        plugin_achievements_threshold: X
        repositories: 1000
        output_action: pull-request

    - name: Achivements
      if: ${{ success() || failure() }}
      uses: lowlighter/metrics@master
      with:
        # Your filename
        filename: img/achivements.svg
        # Your GitHub token
        token: ${{ secrets.METRICS_TOKEN }}
        # Options
        user: felixhollitzer
        template: classic
        base: ""
        config_timezone: Europe/Berlin
        plugin_achievements: yes
        plugin_achievements_display: detailed
        plugin_achievements_threshold: C
        repositories: 1000
        output_action: pull-request

    - name: WakaTime
      if: ${{ success() || failure() }}
      uses: lowlighter/metrics@master
      with:
        # Your filename
        filename: img/wakatime.svg
        # Your GitHub token
        token: ${{ secrets.METRICS_TOKEN }}
        # Options
        user: felixhollitzer
        template: classic
        base: ""
        config_timezone: Europe/Berlin
        plugin_wakatime: yes
        plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
        plugin_wakatime_days: 30
        plugin_wakatime_limit: 5
        plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
        plugin_wakatime_url: https://wakatime.com
        plugin_wakatime_user: current
        output_action: pull-request-squash


