# See https://github.com/lowlighter/metrics for documentation
# This worflow is scheduled for every hour, and also run after each commit (GitHub action excluded) on master/main branch

name: Metrics-Runner
on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  metrics-personal:
    runs-on: ubuntu-latest

    steps:

    #==================================================#
    #                   Template                       #
    #==================================================#
    
    - name: Metrics classic
    if: ${{ success() || failure() }}
    uses: lowlighter/metrics@master
    with:
      # Your filename
      filename: img/metrics.classic.svg
      # Your GitHub token
      token: ${{ secrets.METRICS_TOKEN }}
      # Options
      user: felixhollitzer
      template: classic
      base: ""
      config_timezone: Europe/Berlin
      repositories: 1000
      output_action: pull-request
