# See https://github.com/lowlighter/metrics for documentation
# This worflow is scheduled for every hour, and also run after each commit (GitHub action excluded) on master/main branch

name: Metrics-Runner
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

    - name: Metrics classic
      if: ${{ success() || failure() }}
      uses: lowlighter/metrics@master
      with:
        # Your filename
        filename: img/metrics.classic.svg
        # Your GitHub token
        token: ${{ secrets.METRICS_TOKEN }}
        # Options
        user: felixhollitzer
        template: classic
        base: header, activity, community, repositories, metadata
        config_timezone: Europe/Berlin
        repositories: 1000
        output_action: pull-request


    - name: Metrics terminal
      if: ${{ success() || failure() }}
      uses: lowlighter/metrics@master
      with:
        # Your filename
        filename: img/metrics.terminal.svg
        # Your GitHub token
        token: ${{ secrets.METRICS_TOKEN }}
        # Options
        user: felixhollitzer
        template: terminal
        base: header, activity, community, repositories, metadata
        config_timezone: Europe/Berlin
        repositories: 1000
        output_action: pull-request

    - name: Isometric calendar (half-year)
      if: ${{ success() || failure() }}
      uses: lowlighter/metrics@master
      with:
        # Your filename
        filename: img/half-year.isometric.cal.svg
        # Your GitHub token
        token: ${{ secrets.METRICS_TOKEN }}
        # Options
        user: felixhollitzer
        template: classic
        base: ""
        config_timezone: Europe/Berlin
        plugin_isocalendar: yes
        plugin_isocalendar_duration: half-year
        repositories: 1000
        output_action: pull-request

    - name: Isometric calendar (full-year)
      if: ${{ success() || failure() }}
      uses: lowlighter/metrics@master
      with:
        # Your filename
        filename: img/full-year.isometric.cal.svg
        # Your GitHub token
        token: ${{ secrets.METRICS_TOKEN }}
        # Options
        user: felixhollitzer
        template: classic
        base: ""
        config_timezone: Europe/Berlin
        plugin_isocalendar: yes
        plugin_isocalendar_duration: full-year
        repositories: 1000
        output_action: pull-request-squash

